name = "immortalwrt-base"
base = true

[source]
url = "https://github.com/immortalwrt/immortalwrt.git"
branch = "openwrt-25.12"
depth = 1
submodules = false

[feeds]
update = true
install = true
custom_feeds = []

[build]
download = true
ignore_errors = false

[ccache]
enabled = true
max_size = "10G"
export_stats = true

[output]
calculate_digest = true
