name = "immortalwrt-base"
base = true

[source]
url = "https://github.com/immortalwrt/immortalwrt.git"
branch = "openwrt-25.12"
depth = 1
submodules = false

[build]
download = true
ignore_errors = false

[ccache]
enabled = true
max_size = "3.5G"

[toolchain_cache]
enabled = true
auto_restore = true
auto_save = true

[output]
calculate_digest = true
