name = "uluawrt-mt7981-ax3000m"
extends = "mt798x-base"

[patch]
pre_feeds_patches = ["patch1.py"]
post_feeds_patches = ["patch2.py", "patch3.py"]

[build]
defconfig = "ax3000m.config"

[ccache]
enabled = true

[output]
dist_dir = "uluawrt-mt7981-ax3000m"
target_dir = "bin/targets/mediatek/mt7981"
packages_dir = "bin/packages"
